// ============================================================================
//  PDF generation helpers — uses jspdf (already a project dependency).
// ============================================================================

import { jsPDF } from "jspdf";
import { TZ_COAT_DATA_URI, fmtDate, fmtDateTime } from "./util.js";

// Generate a Request Letter (Utambulisho) PDF for a student.
export function downloadRequestLetterPDF(student, letter, school) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 20;
  const pageW = 210;

  // Header band
  doc.setFillColor(0, 51, 102);
  doc.rect(0, 0, pageW, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("TANZANIA STUDENT IDENTIFICATION SYSTEM", margin, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Jamhuri ya Muungano wa Tanzania  ·  Request Letter (Utambulisho)", margin, 20);
  doc.setFontSize(8);
  doc.text("Ref: " + letter.ref, pageW - margin, 13, { align: "right" });
  doc.text("Date: " + fmtDate(letter.requestedAt), pageW - margin, 20, { align: "right" });

  // Coat of arms (left) + school block (right)
  try {
    doc.addImage(TZ_COAT_DATA_URI, "SVG", margin, 34, 22, 22);
  } catch (e) {
    // fallback rectangle
    doc.setFillColor(255, 215, 0);
    doc.circle(margin + 11, 45, 11, "F");
  }
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text((school && school.name) || student.schoolName, margin + 28, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    [
      "School Code: " + (school && school.code) || student.schoolCode,
      "Region: " + student.region + "   District: " + student.district,
      "Ward: " + student.ward + "   Contact: " + (school && school.contact),
    ],
    margin + 28,
    46
  );

  // Title
  doc.setTextColor(0, 51, 102);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("LETTER OF IDENTIFICATION (UTAMBULISHO)", pageW / 2, 75, {
    align: "center",
  });

  // Body
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const body = [
    "To Whom It May Concern,",
    "",
    "This is to certify that the bearer of this letter, named below, is a bona-fide",
    "student of the above-named institution and is registered with the Tanzania",
    "Student Identification System (TSID).",
    "",
    "Student Name:    " + student.fullname,
    "TSID Number:     " + student.tsid,
    "Date of Birth:   " + fmtDate(student.dob),
    "Gender:          " + student.gender,
    "Nationality:     " + student.nationality,
    "Current Level:   " + student.level,
    "Blood Group:     " + student.bloodGroup,
    "Parent/Guardian: " + student.parentName + " (" + student.relationship + ")",
    "Parent Phone:    " + student.parentPhone,
    "",
    "Purpose of request: " + (letter.reason || "General identification."),
    "",
    "This letter is issued for official identification purposes and should be",
    "treated as a verified document issued under the authority of the school",
    "and the Government of Tanzania through TSID.",
    "",
    "Any inquiry regarding the authenticity of this letter may be directed to",
    "the school contact listed above or via verify.tsid.go.tz.",
  ];
  doc.text(body, margin, 90, { lineHeightFactor: 1.45 });

  // Signature block
  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(0.3);
  doc.line(margin, 230, margin + 60, 230);
  doc.line(pageW - margin - 60, 230, pageW - margin, 230);
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text("Head of Institution", margin, 235);
  doc.text("Official Stamp", pageW - margin - 60, 235);

  // Footer band
  doc.setFillColor(0, 51, 102);
  doc.rect(0, 277, pageW, 20, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(
    "Generated by TSID · Tanzania Student Identification System",
    pageW / 2,
    285,
    { align: "center" }
  );
  doc.text(
    "verify.tsid.go.tz  ·  " + fmtDateTime(letter.requestedAt),
    pageW / 2,
    290,
    { align: "center" }
  );

  doc.save("Utambulisho-" + letter.ref + ".pdf");
}

// Generate a Certificate of Enrollment PDF.
export function downloadCertificatePDF(student, cert, school) {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "landscape" });
  const pageW = 297;
  const pageH = 210;
  const margin = 25;

  // Border
  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(2);
  doc.rect(margin - 8, margin - 8, pageW - 2 * (margin - 8), pageH - 2 * (margin - 8));
  doc.setDrawColor(245, 196, 0);
  doc.setLineWidth(1);
  doc.rect(margin - 4, margin - 4, pageW - 2 * (margin - 4), pageH - 2 * (margin - 4));

  // Header
  doc.setTextColor(0, 51, 102);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("CERTIFICATE OF ENROLLMENT", pageW / 2, 45, { align: "center" });

  try {
    doc.addImage(TZ_COAT_DATA_URI, "SVG", pageW / 2 - 12, 55, 24, 24);
  } catch (e) {}

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(
    "Tanzania Student Identification System (TSID)",
    pageW / 2,
    90,
    { align: "center" }
  );

  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  doc.text("This is to certify that", pageW / 2, 105, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(0, 51, 102);
  doc.text(student.fullname, pageW / 2, 118, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text(
    "bearing TSID Number " + student.tsid + " is a registered student at",
    pageW / 2,
    130,
    { align: "center" }
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  doc.text((school && school.name) || student.schoolName, pageW / 2, 140, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text(
    "in " + student.region + " Region, " + student.district + " District.",
    pageW / 2,
    148,
    { align: "center" }
  );
  doc.text(
    "Current Level: " + student.level + "   ·   Enrolled: " +
      fmtDate(student.enrollmentDate),
    pageW / 2,
    156,
    { align: "center" }
  );

  // Footer
  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(0.3);
  doc.line(margin, 185, margin + 70, 185);
  doc.line(pageW - margin - 70, 185, pageW - margin, 185);
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text("Head of Institution", margin, 190);
  doc.text("Issued: " + fmtDate(cert.issuedAt), pageW - margin - 70, 190);

  doc.setFontSize(8);
  doc.text(
    "Certificate Ref: " + cert.ref,
    pageW / 2,
    200,
    { align: "center" }
  );

  doc.save("Certificate-" + cert.ref + ".pdf");
}

// Generic ID-card PDF print (used by Student ID view + Public search result)
// We rely on window.print() because the existing ID view is already print-optimized.
export function printCardPDF() {
  window.print();
}
